### ISSUE TITLE
MacOSX : Erreur de compilation

### ISSUE THREAD

**Issue by sebmavro** [parazite13/aMAZEd#1]
Voilà le résultat de la tentative de compilation :

Scanning dependencies of target aMAZEd
[ 50%] Building CXX object CMakeFiles/aMAZEd.dir/main.cpp.o
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
[100%] Linking CXX executable aMAZEd
clang: error: unsupported option '-static-libgcc'
make[2]: *** [aMAZEd] Error 1
make[1]: *** [CMakeFiles/aMAZEd.dir/all] Error 2
make: *** [all] Error 2

**Comment by parazite13** [comment]
L'option de compilation en question était inutile elle est donc était retirée lors du commit [91f3358cf26f87d6a9d51a7ddf30bdcf4b6d426f](https://github.com/parazite13/aMAZEd/commit/91f3358cf26f87d6a9d51a7ddf30bdcf4b6d426f)

**Comment by sebmavro** [comment]
C'est réglé !
